"""Generate static pages for the AutoPaginas Mundial project.

This script reads a configuration file (config.json) describing
the different categories to generate. Each category entry
specifies a slug (used for the filename), a title, a description,
the type of content (bios, names or phrases), the language and
optionally a style for phrases.

Running this script will populate the ``docs`` directory with
HTML pages for each category and an index page linking to them.

The generated lists are created on‑the‑fly using simple
combinatorial logic so the output changes with each run. For
example, names are generated by combining an adjective with a
noun, bios are composed of an introduction, a descriptor and a
closing sentence, and phrases are built from two complementary
halves.

The goal of this project is to demonstrate how a self‑updating
site could be built without any external APIs. You can add or
modify categories in ``config.json`` to further tailor the
generated content. To deploy the site on GitHub Pages you can
commit this repository to a public GitHub repository and enable
Pages on the ``docs`` directory.
"""

from __future__ import annotations

import json
import os
import random
from pathlib import Path

# Wallet address used for donations. This constant will be inserted
# into every generated page so that anyone visiting the site can
# support the project directly. Update this value if the wallet
# changes.
WALLET_ADDRESS = "0xDC6740245e026A19ea9EE2B62968ea8aeFFEAb16"


# Data pools for content generation

# English data
ADJECTIVES_EN = [
    "Quantum", "Neon", "Cosmic", "Hyper", "Mega", "Solar", "Lunar",
    "Crypto", "Tech", "Cyber", "Atomic", "Galaxy", "Swift", "Crimson",
    "Electric", "Phantom", "Futuristic", "Pixel", "Nexus", "Apex",
    "Binary", "Digital", "Infinite", "Viral", "Dynamic"
]

NOUNS_EN = [
    "Coders", "Hackers", "Pioneers", "Warriors", "Titans", "Innovators",
    "Dragons", "Mavericks", "Pirates", "Wizards", "Ninjas", "Guardians",
    "Rangers", "Rockets", "Gamers", "Voyagers", "Explorers", "Builders",
    "Champions", "Creators"
]

BIO_INTROS_EN = [
    "Just a", "Coffee lover by day,", "On a mission to", "Living life",
    "Dreaming big and", "Weaving code and", "Sharing my journey of",
    "Searching for", "Part‑time", "Full‑time"
]

BIO_DESCRIPTORS_EN = [
    "techie with a love for music", "creative soul exploring the universe",
    "digital nomad chasing sunsets", "pet parent and proud",
    "foodie exploring flavours", "bookworm with a twist",
    "gamer with zero chill", "fitness enthusiast with a sweet tooth",
    "life‑long learner and teacher", "storyteller in the making"
]

BIO_CLOSERS_EN = [
    "Follow along!", "Join me!", "Stay tuned.", "Let’s connect.",
    "Here for good vibes.", "Onwards and upwards.", "Creating my dream life.",
    "Let's ride this wave.", "No regrets, just lessons.", "Still figuring it all out."
]

PHRASE_INTROS_EN = {
    "inspirational": [
        "Believe in", "Chase your", "Every day is", "Success is",
        "Life is", "Happiness is", "Never forget", "Love is", "Keep",
        "Embrace"
    ],
    "funny": [
        "I’m not lazy,", "Why do they call it rush hour when",
        "I’m on a whiskey", "If life gives you lemons,",
        "I’m reading a book on", "I told my computer I needed a break, and it",
        "Maybe if we all", "I’m on a seafood diet:", "Common sense is like",
        "I put my phone in Airplane mode but"
    ]
}

PHRASE_CLOSERS_EN = {
    "inspirational": [
        "the magic within.", "a new beginning.", "a state of mind.",
        "a journey, not a destination.", "about learning and growing.",
        "a choice, not a result.", "to be yourself.",
        "always around the corner.", "pushing forward.",
        "your inner strength."
    ],
    "funny": [
        "I’m on energy‑saving mode.", "the traffic moves at a snail’s pace?",
        "diet; I need no improvement.", "throw them back and ask for chocolate.",
        "anti‑gravity—it’s impossible to put down!", "locked me out.",
        "slowed down, we’d have more time to think.", "I eat it!",
        "deodorant; the people who need it never use it.", "it didn’t fly!"
    ]
}

# Spanish data
ADJECTIVES_ES = [
    "Cuántico", "Neón", "Cósmico", "Hipernova", "Mega", "Solar", "Lunar",
    "Cripto", "Tecnológico", "Cibernético", "Atómico", "Galáctico", "Rápido",
    "Carmesí", "Eléctrico", "Fantasma", "Futurista", "Pixelado", "Nexo", "Ápex"
]

NOUNS_ES = [
    "Programadores", "Hackers", "Pioneros", "Guerreros", "Titanes", "Innovadores",
    "Dragones", "Mavericks", "Piratas", "Magos", "Ninjas", "Guardianes",
    "Rangers", "Cohetes", "Jugadores", "Exploradores", "Constructores",
    "Campeones", "Creadores"
]

BIO_INTROS_ES = [
    "Solo un(a)", "Amante del café de día y", "En una misión para", "Viviendo la vida",
    "Soñando en grande y", "Tejiendo código y", "Compartiendo mi viaje de",
    "Buscando", "Parte de mi vida es", "A tiempo completo"
]

BIO_DESCRIPTORS_ES = [
    "tecnólogo/a con amor por la música", "alma creativa explorando el universo",
    "nómada digital persiguiendo atardeceres", "padre/madre de mascotas orgulloso/a",
    "amante de la comida explorando sabores", "ratón de biblioteca con un toque",
    "jugador/a con cero paciencia", "entusiasta del fitness con gusto por lo dulce",
    "aprendiz de por vida y profesor/a", "contador/a de historias en desarrollo"
]

BIO_CLOSERS_ES = [
    "¡Sígueme!", "¡Únete!", "Mantente al tanto.", "Conectemos.",
    "Aquí por las buenas vibras.", "Hacia arriba y adelante.",
    "Creando mi vida soñada.", "Vamos a surfear esta ola.",
    "Sin arrepentimientos, solo lecciones.", "Aún descifrándolo todo."
]

PHRASE_INTROS_ES = {
    "inspirational": [
        "Cree en", "Persigue tus", "Cada día es", "El éxito es",
        "La vida es", "La felicidad es", "Nunca olvides", "El amor es", "Sigue",
        "Abraza"
    ],
    "funny": [
        "No soy perezoso/a,", "¿Por qué llaman hora pico cuando",
        "Estoy en una dieta de", "Si la vida te da limones,",
        "Estoy leyendo un libro sobre", "Le dije a mi ordenador que necesitaba un descanso y",
        "Quizá si todos", "Estoy en una dieta de mariscos:", "El sentido común es como",
        "Puse mi teléfono en modo avión, pero"
    ]
}

PHRASE_CLOSERS_ES = {
    "inspirational": [
        "la magia interior.", "un nuevo comienzo.", "un estado mental.",
        "un viaje, no un destino.", "aprender y crecer.", "una elección, no un resultado.",
        "ser tú mismo/a.", "siempre está cerca.", "adelante.", "tu fuerza interior."
    ],
    "funny": [
        "estoy en modo ahorro de energía.", "el tráfico va a paso de tortuga?",
        "whisky; no necesito mejorar.", "devuélvelos y pide chocolate.",
        "antigravedad—es imposible dejarlo.", "me bloqueó.",
        "disminuimos, tendríamos más tiempo para pensar.", "veo comida y me la como!",
        "desodorante; las personas que lo necesitan nunca lo usan.", "¡no voló!"
    ]
}


def random_name(language: str) -> str:
    """Generate a random team or username depending on the language."""
    if language == "es":
        return f"{random.choice(ADJECTIVES_ES)} {random.choice(NOUNS_ES)}"
    # default to English
    return f"{random.choice(ADJECTIVES_EN)} {random.choice(NOUNS_EN)}"


def random_bio(language: str) -> str:
    """Generate a random bio composed of intro, descriptor and closer."""
    if language == "es":
        intro = random.choice(BIO_INTROS_ES)
        descriptor = random.choice(BIO_DESCRIPTORS_ES)
        closer = random.choice(BIO_CLOSERS_ES)
    else:
        intro = random.choice(BIO_INTROS_EN)
        descriptor = random.choice(BIO_DESCRIPTORS_EN)
        closer = random.choice(BIO_CLOSERS_EN)
    # Use a comma after the descriptor to mirror the English style. Spanish
    # grammar tolerates the same structure for these simple sentences.
    return f"{intro} {descriptor}, {closer}"


def random_phrase(language: str, style: str = "inspirational") -> str:
    """Generate a random phrase based on language and style (inspirational or funny)."""
    style_key = style if style in PHRASE_INTROS_EN else "inspirational"
    if language == "es":
        intro_pool = PHRASE_INTROS_ES.get(style_key, PHRASE_INTROS_ES["inspirational"])
        closer_pool = PHRASE_CLOSERS_ES.get(style_key, PHRASE_CLOSERS_ES["inspirational"])
    else:
        intro_pool = PHRASE_INTROS_EN.get(style_key, PHRASE_INTROS_EN["inspirational"])
        closer_pool = PHRASE_CLOSERS_EN.get(style_key, PHRASE_CLOSERS_EN["inspirational"])
    return f"{random.choice(intro_pool)} {random.choice(closer_pool)}"


def generate_items(category: dict) -> list[str]:
    """Generate a list of 100 items for a given category."""
    kind = category.get("kind")
    lang = category.get("language", "en")
    style = category.get("style", "inspirational")
    items: list[str] = []
    if kind == "names":
        items = [random_name(lang) for _ in range(100)]
    elif kind == "bios":
        items = [random_bio(lang) for _ in range(100)]
    elif kind == "phrases":
        items = [random_phrase(lang, style) for _ in range(100)]
    return items


def create_page(category: dict, items: list[str]) -> None:
    """Create an HTML page for a category with the generated items.

    Pages are written into the top‑level ``docs`` directory next to
    the ``generator`` folder. Using an absolute path relative to this
    script’s parent directory ensures the output location is
    consistent regardless of the current working directory.
    """
    slug = category["slug"]
    title = category["title"]
    description = category.get("description", "")
    language = category.get("language", "en")
    # Build list items HTML
    list_html = "\n        ".join(f"<li>{item}</li>" for item in items)
    # Choose placeholder text based on language
    search_placeholder = "Buscar..." if language == "es" else "Search..."
    # Build a donation block HTML with copy button. The copy
    # functionality uses the Clipboard API available in modern
    # browsers. If unsupported it simply does nothing.
    # Build a donation section that does not rely on any third‑party widgets.  In
    # addition to showing the wallet address and providing a copy button, we
    # also include an explicit `ethereum:` link.  Clicking this link will
    # trigger supported wallets (e.g. MetaMask) to prepare a transfer to the
    # specified address.  This approach keeps the site entirely self‑hosted
    # and avoids dependencies on external payment providers.
    donation_html = f"""
    <div class=\"adslot\">
      <p><strong>¿Te gusta este sitio?</strong> Si quieres apoyarlo, puedes enviar
      una contribución directamente a la billetera del proyecto:</p>
      <p><code>{WALLET_ADDRESS}</code></p>
      <button onclick=\"navigator.clipboard.writeText('{WALLET_ADDRESS}')\">Copiar dirección</button>
      <p><a href=\"ethereum:{WALLET_ADDRESS}\" target=\"_blank\">Abrir en tu monedero (MetaMask u otro)</a></p>
    </div>
    """
    page_html = f"""<!DOCTYPE html>
<html lang=\"{language}\">
<head>
    <meta charset=\"utf-8\">
    <title>{title}</title>
    <meta name=\"description\" content=\"{description}\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <link rel=\"stylesheet\" href=\"assets/style.css\">
    <script>
    function filterList() {{
        const input = document.getElementById('searchInput');
        const filter = input.value.toLowerCase();
        const items = document.querySelectorAll('#items li');
        items.forEach(item => {{
            const text = item.textContent.toLowerCase();
            item.style.display = text.includes(filter) ? '' : 'none';
        }});
    }}
    </script>
</head>
<body>
    <h1>{title}</h1>
    <p>{description}</p>
    <input type=\"text\" id=\"searchInput\" class=\"search\" placeholder=\"{search_placeholder}\" oninput=\"filterList()\">
    <div class=\"adslot\">Zona de monetización</div>
    <ul id=\"items\">
        {list_html}
    </ul>
    {donation_html}
    <p><a href=\"index.html\">Inicio / Home</a></p>
</body>
</html>"""
    # Determine the base directory (one level up from this file)
    base_dir = Path(__file__).resolve().parents[1]
    docs_dir = base_dir / 'docs'
    docs_dir.mkdir(parents=True, exist_ok=True)
    file_path = docs_dir / f"{slug}.html"
    with file_path.open('w', encoding='utf-8') as f:
        f.write(page_html)


def create_index(categories: list[dict]) -> None:
    """Create the index page linking to all category pages.

    The index is placed in the top‑level ``docs`` directory. It lists
    each category with a link and indicates the language for quick
    reference. Adjust the introductory paragraph as desired.
    """
    links: list[str] = []
    for cat in categories:
        slug = cat['slug']
        title = cat['title']
        lang = cat.get('language', 'en')
        links.append(f"<li><a href=\"{slug}.html\">{title} ({lang.upper()})</a></li>")
    list_html = "\n        ".join(links)
    index_html = f"""<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"utf-8\">
    <title>AutoPaginas Mundial - Fábrica de Microutilidades</title>
    <meta name=\"description\" content=\"Global long‑tail content generator\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <link rel=\"stylesheet\" href=\"assets/style.css\">
</head>
<body>
    <h1>AutoPaginas Mundial</h1>
    <p>Bienvenido/a a la Fábrica de Microutilidades. Encuentra listas generadas automáticamente en múltiples idiomas y categorías. Actualizamos el contenido a diario para que siempre tengas ideas frescas.</p>
    <ul>
        {list_html}
    </ul>
    <p>Desarrollado con ❤ con Python. Inserta tus scripts de anuncios o botones de donaciones en los espacios de monetización de cada página.</p>
    <p><strong>¿Te gusta este proyecto?</strong> Si quieres apoyarlo puedes enviar una contribución a la siguiente billetera:</p>
    <p><code>{WALLET_ADDRESS}</code></p>
    <button onclick=\"navigator.clipboard.writeText('{WALLET_ADDRESS}')\">Copiar dirección</button>
    <p><a href=\"ethereum:{WALLET_ADDRESS}\" target=\"_blank\">Abrir en tu monedero (MetaMask u otro)</a></p>
</body>
</html>"""
    # Determine base docs directory
    base_dir = Path(__file__).resolve().parents[1]
    docs_dir = base_dir / 'docs'
    docs_dir.mkdir(parents=True, exist_ok=True)
    with (docs_dir / 'index.html').open('w', encoding='utf-8') as f:
        f.write(index_html)


def main() -> None:
    # Determine current working directory and locate config file
    config_path = Path(__file__).with_name('config.json')
    with config_path.open('r', encoding='utf-8') as f:
        categories = json.load(f)
    # Generate content for each category
    for category in categories:
        items = generate_items(category)
        create_page(category, items)
    create_index(categories)


if __name__ == '__main__':
    main()